
export const DURgridProps = {
    records: [
      {
        jobId: 'GE South',
        layouts: '2',
        docs: '276',
        amount: 50000,
        emboldened: true,
        subRecords: [
          {
            documentId: '1029653',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029654',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029655',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
        ],
      },
      {
        jobId: 'Wells Fargo New England',
        layouts: '2',
        docs: '276',
        amount: 50000,
        emboldened: true,
        subRecords: [
          {
            documentId: '1029656',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029657',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029658',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
        ],
      },
      {
        jobId: 'Wells Fargo West',
        layouts: '2',
        docs: '276',
        amount: 50000,
        emboldened: true,
        subRecords: [
          {
            documentId: '1029650',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029653',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029660',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
        ],
      },
      {
        jobId: 'GE North',
        layouts: '2',
        docs: '276',
        amount: 50000,
        subRecords: [
          {
            documentId: '1029661',
            pages: '2',
            amount: 40000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029662',
            pages: '5',
            amount: 5000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029663',
            pages: '89',
            amount: 5000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
        ],
      },
      {
        jobId: 'IBM Northwest',
        layouts: '2',
        docs: '276',
        amount: 50000,
        subRecords: [
          {
            documentId: '1029666',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029667',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
          {
            documentId: '1029668',
            pages: '2',
            amount: 10000,
            layoutType: 'Check Layout',
            claimId: '1035810392',
          },
        ],
      },
    ],
    columns: new Set([
      {
        dataName: 'jobId',
        text: 'Job Id',
        sortable: false,
        isSorted: 0,
      },
      {
        dataName: 'layouts',
        text: 'Layout',
        sortable: false,
        isSorted: 0,
      },
      {
        dataName: 'docs',
        text: 'Docs',
        sortable: false,
        isSorted: 0,
      },
      {
        dataName: 'amount',
        text: 'Amount',
        sortable: false,
        isSorted: 0,
        isCurrency: true,
      },
      {
        dataName: 'jobId',
        text: 'Job Id',
        sortable: false,
        isSorted: 0,
      },
      {
        dataName: 'layouts',
        text: 'Layout',
        sortable: false,
        isSorted: 0,
      },
      {
        dataName: 'docs',
        text: 'Docs',
        sortable: false,
        isSorted: 0,
      },
      {
        dataName: 'amount',
        text: 'Amount',
        sortable: false,
        isSorted: 0,
        isCurrency: true,
      }
    ]),
    selectedItemIds: new Set([]),
    selectionKey: 'jobId',
    domId: 'grid',
    onSortTableColumn: () => {alert('Sort table column');},
    onRowSelect: () => {},
    onSelectAll: () => {},
    onLinkClick: () => {},
    onSettingsCancel: () => {},
    supportSelection: false,
    isConfigurable: true,
  };

  export default DURgridProps;